// ===== Member Data - Single Source of Truth =====
// This file contains all student data extracted from the original index.js

export const membersArray = [
  {
    name: "Anika Tabassum",
    id: "2404001",
    home: "Cumilla",
    college: "Feni Girls' Cadet College",
    school: "Feni Girls' Cadet College",
    bio: null,
    nickname: "Anika",
    fb_profile_link: "https://www.facebook.com/share/19fXmd7n5o/",
  },
  {
    name: "Hafsa Khanom",
    id: "2404002",
    home: "Chittagong",
    college: "Chittagong Govt. Women's College",
    school: "Dr. Khastagir Govt. Girls' High School",
    bio: "A believer striving in the way of Allah.",
    nickname: "Hafsa",
    fb_profile_link: "https://www.facebook.com/profile.php?id=61578623584686",
  },
  {
    name: "Md. Abrar Fairuj Raiyan",
    id: "2404003",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Tahmid Moontaka",
    id: "2404004",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Sayantan Sen Sarma",
    id: "2404005",
    home: "Chattogram",
    college: "Chattogram College",
    school: "Chattogram Collegiate School",
    bio: null,
    nickname: "Sayantan",
    fb_profile_link: "https://www.facebook.com/share/1FzMujfaKo/",
  },
  {
    name: "Md.Montasir Shakil",
    id: "2404006",
    home: "Chattogram",
    college: "Bakalia Government College",
    school: "Nasirabad Government Boys High school",
    bio: "I am an undergraduate CSE Student at CUET. Aspiring Software Engineer | AI/ML Enthusiast. Also passionate about Robotics",
    nickname: "Montasir",
    fb_profile_link: "https://www.facebook.com/share/17BLooa6CW/",
  },
  {
    name: "Sk. Tasmia Akter",
    id: "2404007",
    home: "Ctg",
    college: "Govt. Hazi Muhammad Mohsin College",
    school: "St. Scholastica's Girls School and College",
    bio: null,
    nickname: "Tanha",
    fb_profile_link: "https://www.facebook.com/share/1FHLfvxWRx/",
  },
  {
    name: "Tahia Rabab",
    id: "2404008",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Md Sazzat Nur",
    id: "2404009",
    home: "Cumilla",
    college: "Notre Dame College",
    school: "Pir Kashimpur r.n. high school",
    bio: "Student",
    nickname: "Sazzat",
    fb_profile_link: "https://www.facebook.com/share/1JYeR8MAL4/",
  },
  {
    name: "Tanjila Kamal",
    id: "2404010",
    home: "Chittagong",
    college: "Chittagong College",
    school: "Dr. Khastagir Govt. Girls' High School",
    bio: null,
    nickname: "Tanjila",
    fb_profile_link: null,
  },
  {
    name: "Mohtasim Bhuiyan Mikat",
    id: "2404011",
    home: "Brahmonbaria",
    college: "Notre Dame College",
    school: "NKM High School and Homes",
    bio: "I am just a ordinary boy from a middle class family who is just trying to enjoy his life as far he can .just one piece of advice that just avoid yourself from shitty people and go ahead , life is so beutiful.",
    nickname: "Mikat",
    fb_profile_link: "https://www.facebook.com/share/16xGeF8cA1/",
  },
  {
    name: "Alikul Islam Alif",
    id: "2404012",
    home: "Cox's bazar",
    college: "Chattogram Cantonment Public College",
    school: "Chakaria Korak Biddyapith",
    bio: "CSE24",
    nickname: "Alif",
    fb_profile_link: "https://www.facebook.com/share/1Aj6rJYr3H/",
  },
  {
    name: "Joyee Dev",
    id: "2404013",
    home: "Chittagong",
    college: "Chittagong College",
    school: "BMS girls' high school & College",
    bio: null,
    nickname: "Joyee",
    fb_profile_link: "https://www.facebook.com/share/1FJCccUUrT/",
  },
  {
    name: "Tamanna Khanam Joti",
    id: "2404014",
    home: "Rajbari",
    college: "Chittagong College",
    school: "Dr. Khastagir Govt. Girls' High School",
    bio: null,
    nickname: "Joti",
    fb_profile_link: "https://www.facebook.com/share/16yuAo7CKV/",
  },
  {
    name: "Samiya Ahmed Chowdhury",
    id: "2404015",
    home: "chittagong",
    college: "chattogram college",
    school: "Dr. khastagir govt. girls high school",
    bio: "I am samiya.I enjoy learning new skills, exploring creative ideas, and spending my free time watching anime.",
    nickname: "samiya",
    fb_profile_link: "https://www.facebook.com/samiya.ahmed.247470",
  },
  {
    name: "Md. Jomman",
    id: "2404016",
    home: "Brahmanbaria",
    college: "St. Joseph Higher Secondary School",
    school: "Bitghar Radha Nath High School",
    bio: "Love to code",
    nickname: "Jomman",
    fb_profile_link: null,
  },
  {
    name: "Soumik Dutta",
    id: "2404017",
    home: "Chattogram",
    college: "Notre Dame College",
    school: "Chattogram Collegiate School",
    bio: null,
    nickname: "Soumik",
    fb_profile_link: "https://www.facebook.com/share/19KQUeHd5r/",
  },
  {
    name: "Muqset Hossain Mahin",
    id: "2404018",
    home: "Narsingdi",
    college: "NDC",
    school: "Islampur ML High School",
    bio: '"Time doesn\'t heal anything, it just teaches us how to live with pain." - Itachi Uchiha',
    nickname: "Mahin",
    fb_profile_link: "https://www.facebook.com/share/1ZEZG1iS3U/",
  },
  {
    name: "Sharid Shahria Miraj",
    id: "2404019",
    home: "Gazipur",
    college: "Gazipur Cantonment College, BOF",
    school: "Rani Bilasmoni Government Boys High School, Gazipur",
    bio: null,
    nickname: "Miraj",
    fb_profile_link: "https://www.facebook.com/bm.shahriar.56",
  },
  {
    name: "Rahul Banik",
    id: "2404020",
    home: "Sunamganj",
    college: "MC college, sylhet",
    school: "Govt. Jubilee high school, Sunamganj",
    bio: null,
    nickname: "Rahul",
    fb_profile_link: "https://www.facebook.com/share/1CXz4Kh8qe/",
  },
  {
    name: "Md Abdullah Al Aziz",
    id: "2404021",
    home: "Chattogram",
    college: "Chattogram Cantonment Public College",
    school: "Ispahani High School",
    bio: null,
    nickname: "Adiz",
    fb_profile_link: "https://www.facebook.com/share/1AxvPyAoQA/",
  },
  {
    name: "Aditya Mitra",
    id: "2404022",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Mohammad Adnan Foisal",
    id: "2404023",
    home: "Chattogram",
    college: "Hazera tazu degree College",
    school: "Chittagong Goct High Schoo",
    bio: "Always hungry for more knowledge",
    nickname: "Adnan",
    fb_profile_link: null,
  },
  {
    name: "Prapti Roy Chowdhury",
    id: "2404024",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Fardin Khan Rifat",
    id: "2404025",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Farhana Akter Srety",
    id: "2404026",
    home: "Lakshmipur",
    college: "Firoza Bashar Ideal College",
    school: "Birahimpur High School",
    bio: "Life has turned into Bioscope while choosing bio.",
    nickname: "Srety",
    fb_profile_link: "https://www.facebook.com/share/15rkPVWAdC/",
  },
  {
    name: "Mohammad Ekra",
    id: "2404027",
    home: "Feni",
    college: "National Ideal College",
    school: "Ideal School and College",
    bio: "Nothing",
    nickname: "Ekra",
    fb_profile_link: "https://www.facebook.com/000mdekra000",
  },
  {
    name: "Souvik Biswas",
    id: "2404028",
    home: "Faridpur",
    college: "St. Joseph Higher Secondary School",
    school: "Faridpur Zilla School",
    bio: null,
    nickname: "Souvik",
    fb_profile_link: "https://www.facebook.com/roronoa.rongon",
  },
  {
    name: "Arpita Baishnab",
    id: "2404029",
    home: "Noakhali",
    college: "Holy Cross College, Dhaka",
    school: "Basurhat A.H.C. Govt. High School,Companiganj, Noakhali",
    bio: null,
    nickname: "Badhan",
    fb_profile_link: "https://www.facebook.com/share/1CCxpjNXWi/",
  },
  {
    name: "Chomok Datta",
    id: "2404030",
    home: "Moulvibazar",
    college: "Moulvibazar Govt College",
    school: "Moulvibazar Govt High School",
    bio: null,
    nickname: "Arnob",
    fb_profile_link: null,
  },
  {
    name: "Taslima Jahan Bithi",
    id: "2404031",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Tonoy Chandra Pal",
    id: "2404032",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Palash biswas",
    id: "2404033",
    home: "Magura",
    college: "Sreepur govt College",
    school: "Gangnalia high school",
    bio: "Palash biswas,CSE -24, CUET,magura sadar,magura",
    nickname: "Palash",
    fb_profile_link: "https://www.facebook.com/share/16pPXE7dQE/",
  },
  {
    name: "Anik Dey",
    id: "2404034",
    home: "ctg",
    college: "CCPC",
    school: "A L KHAN HIGH SCHOOL",
    bio: null,
    nickname: "Anik",
    fb_profile_link: "https://www.facebook.com/anika.de.640225",
  },
  {
    name: "Rupak Chakrabarty Ankon",
    id: "2404035",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Israt Jahan",
    id: "2404036",
    home: "Feni",
    college: "Govt. Mohammad Mohsin College",
    school: "Silver Bells Girl's High School",
    bio: null,
    nickname: "Israt",
    fb_profile_link: "https://www.facebook.com/share/19tG3tSiER/",
  },
  {
    name: "Rafsan Ahmed",
    id: "2404037",
    home: "Madaripur",
    college: "Rajuk Uttara Model College",
    school: "Rajuk Uttara Model College",
    bio: "I am just a random guy with no skills and no notable achievements trying to get out of this ratrace",
    nickname: "Rafsan",
    fb_profile_link: "https://www.facebook.com/share/1Vw92RVqm7/",
  },
  {
    name: "Fahim Muntasir Tuhin",
    id: "2404038",
    home: "Sunamganj",
    college: "Jalalabad Cantonment public school and college",
    school: "Jur govt.high school",
    bio: "Nihilist",
    nickname: "Fahim",
    fb_profile_link: "https://www.facebook.com/share/1EmadJdwso/",
  },
  {
    name: "Arian Ahmed Robi",
    id: "2404039",
    home: "Khulna",
    college: "Brajalal College, Khulna",
    school: "Khulna power station high school",
    bio: "I am a student of cuet.(Department of Computer Science & Engineering)",
    nickname: "Arian",
    fb_profile_link: "https://www.facebook.com/share/178rBdPxQY/",
  },
  {
    name: "Payel Mallick",
    id: "2404040",
    home: "Chittagong",
    college: "Chittagong college",
    school: "Aparnacharan City Corporation Girls' High School and College",
    bio: null,
    nickname: "Payel",
    fb_profile_link: null,
  },
  {
    name: "Suravy Rani Datta",
    id: "2404041",
    home: "Lakshmipur",
    college: "Lakshmipur Government College",
    school: "Lakshmipur Government Girls' High School",
    bio: "Turning 0s and 1s into something magical.",
    nickname: "Suravy",
    fb_profile_link: "https://www.facebook.com/suravy.datta",
  },
  {
    name: "Nusrat Jahan Maya",
    id: "2404042",
    home: "Rajshahi",
    college: "Holy Cross College",
    school: "Daffodils High School",
    bio: "Innovative Software & AI Enthusiast",
    nickname: "Maya",
    fb_profile_link: "https://www.facebook.com/share/14FPxR9zBTd/",
  },
  {
    name: "Arunav Dip Arko",
    id: "2404043",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Md. Mahfuz Hasan",
    id: "2404044",
    home: "Gaibandha",
    college: "Sylhet govt. College",
    school: "Shahjalal NGFF School",
    bio: "I want to be a programer.",
    nickname: "Mahfuz",
    fb_profile_link: "https://www.facebook.com/share/19oMWSFQoj/",
  },
  {
    name: "MD. TANVIR RANA TUHIN",
    id: "2404045",
    home: "THAKURGAON",
    college: "NOTRE DAME COLLEGE, DHAKA",
    school: "MOTIJHEEL GOVT. HIGH SCHOOL & COLLEGE",
    bio: null,
    nickname: "TUHIN",
    fb_profile_link: "https://www.facebook.com/tanvir.rana.779205/",
  },
  {
    name: "Mahmudul Hasan Rafti",
    id: "2404046",
    home: "Mymensingh",
    college: "Govt. Ananda Mohon College",
    school: "Gafargaon Islamia Govt. High School",
    bio: null,
    nickname: "Rafti",
    fb_profile_link:
      "https://www.facebook.com/mahmudulhasan.rafti?mibextid=ZbWKwL",
  },
  {
    name: "Afif Al Hasnain",
    id: "2404047",
    home: "Chittagong",
    college: "Govt. Hazi Mohammad Mohsin College",
    school: "Nasirabad Govt. Boys Highschool",
    bio: "Highly motivated to do nothing.",
    nickname: "Afif",
    fb_profile_link: "https://www.facebook.com/afifal.hasnain",
  },
  {
    name: "Rihan Rahman Abir",
    id: "2404048",
    home: "Brahmonbaria",
    college: "BN College, CTG",
    school: "BN School & College, CTG",
    bio: null,
    nickname: "Rihan",
    fb_profile_link: "https://www.facebook.com/share/1BzaFYWNoJ/",
  },
  {
    name: "Khadiza Tul Kubra Todra",
    id: "2404049",
    home: "JAMALPUR",
    college: "Rajuk Uttara Model College",
    school: "Viqarunnisa Noon School and College",
    bio: null,
    nickname: "Khadiza",
    fb_profile_link: "https://www.facebook.com/share/175SkmWv6r/",
  },
  {
    name: "Suvha Tabassum",
    id: "2404050",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Khandaker Badar Uddin Munim",
    id: "2404051",
    home: "Narsingdi",
    college: "Govt.Science College,Tejgaon",
    school: "Brahmondi K. K. M. Govt.High School",
    bio: "Breathing",
    nickname: "Munim",
    fb_profile_link: "https://www.facebook.com/khandaker.munim.2025",
  },
  {
    name: "Sadia Sultana",
    id: "2404052",
    home: "Chittagong",
    college: "Chittagong College",
    school: "Dr.Khastagir govt. girls' high school",
    bio: "🙂😮‍💨🫠😶‍🌫️",
    nickname: "Sadia",
    fb_profile_link: "https://www.facebook.com/share/1Fd7a64jAR/",
  },
  {
    name: "Prothoy Mallick",
    id: "2404053",
    home: "Chittagong",
    college: "Chittagong college",
    school: "St. Placid's school and college",
    bio: "I am just a chill guy",
    nickname: "Prothoy",
    fb_profile_link: "https://www.facebook.com/share/19dzY6mdxH/",
  },
  {
    name: "Mohd Taj Uddin Mahmud Chy Abir",
    id: "2404054",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Md Hasibul Kabir",
    id: "2404055",
    home: "Bagerhat",
    college: "Dhaka Residential Model College",
    school: "Shaheed Police Smrity College",
    bio: "I like to sleep.",
    nickname: "Hasib",
    fb_profile_link: "https://m.facebook.com/mdhasibulkabir.hasib/",
  },
  {
    name: "Umme Salma Fariha",
    id: "2404056",
    home: "Cumilla",
    college: "Cumilla Victoria Govt. College",
    school: "Cumilla Modern High School",
    bio: null,
    nickname: "Fariha",
    fb_profile_link: "https://www.facebook.com/share/19BM4T95ud/",
  },
  {
    name: "Rahimul Hoque",
    id: "2404057",
    home: "Dhaka",
    college: "Savar Cantonment Public School and College",
    school: "Savar Cantonment Public School and College",
    bio: "Aiming high💪",
    nickname: "Rahimul",
    fb_profile_link: "https://www.facebook.com/share/1ZbVYNiiGH/",
  },
  {
    name: "Puspita Dash",
    id: "2404058",
    home: "Habiganj",
    college: "Brindabon Govt. College, Habiganj",
    school: "B.K.G.C. Govt. Girls' High School, Habiganj",
    bio: null,
    nickname: "Puspita",
    fb_profile_link: "https://www.facebook.com/share/1As9f3gUUf/",
  },
  {
    name: "Ifrat Jahan Chowdhury",
    id: "2404059",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Umme Rubaiyat Trina",
    id: "2404060",
    home: "Mymensingh",
    college: "Chattogram government model school and college",
    school: "Chattogram government model school and college",
    bio: "Umme Rubaiyat Trina is a student with a growing passion for tech and programming. She's been building her skills in C, C++, HTML, and CSS, and enjoys exploring how code can bring ideas to life. Always curious and eager to learn, Trina is excited to keep expanding her knowledge and take on new challenges in the world of technology.",
    nickname: "Trina",
    fb_profile_link: "https://www.facebook.com/share/16NHM6n2DC/",
  },
  {
    name: "Md. Tanveer Islam Jishan",
    id: "2404061",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Sumaya Sadath Rodia",
    id: "2404062",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Md. Rakibul Islam Rakib",
    id: "2404063",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "A.K.M. Musfiqul Islam",
    id: "2404064",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "S.M. Mahdi Hasan",
    id: "2404065",
    home: "Habiganj",
    college: "Brindaban Government College",
    school: "Loknath Ramanbihari Govt High School",
    bio: "As is an aspiring computer science student at CUET, passionate about physics, mathematics, technology, and history. Currently exploring programming with C++ and Python, they also run an e-commerce business selling custom-designed notebooks. With a calm, analytical personality and a drive for deeply educational content, As plans to launch a YouTube channel to make complex ideas accessible to teenagers and beginners. Their interests extend to AI, machine learning, and innovative ed-tech projects for the future.",
    nickname: "Disan",
    fb_profile_link: "https://www.facebook.com/sheikh.mahdi.92167",
  },
  {
    name: "Shishir Basak",
    id: "2404066",
    home: "Mymensingh",
    college: "Notre Dame College Mymensingh",
    school: "Mukul Niketon High School, Mymensingh",
    bio: null,
    nickname: "Shishir",
    fb_profile_link: "https://www.facebook.com/shishir.basak.14",
  },
  {
    name: "Tasfia Tabassum",
    id: "2404067",
    home: null,
    college: null,
    school: null,
    bio: null,
    nickname: null,
    fb_profile_link: null,
  },
  {
    name: "Tithi Mutsuddi",
    id: "2404068",
    home: "Chattogram",
    college: "Govt. City College, Chattogram",
    school: "Dr. Khastagir Govt. Girls' High School",
    bio: "nothing glorious to say yet ;)",
    nickname: "Tithi",
    fb_profile_link: "https://www.facebook.com/share/1EW4gjAy8x/",
  },
  {
    name: "Antar Karmakar Aorgha",
    id: "2404073",
    home: "Chandpur",
    college: "Notre Dame College,Dhaka",
    school: "Hasan Ali Govt.High School",
    bio: "It's Nice to have some break from this hectic life.",
    nickname: "Aorgha",
    fb_profile_link: "https://www.facebook.com/aorgha.karmakar",
  },
  {
    name: "Ahnab Ahmed",
    id: "2404074",
    home: "Dhaka",
    college: "Milestone college",
    school: "National ideal school",
    bio: "I am ahnab , currently pursuing computer science and engineer at cuet",
    nickname: "Sijan",
    fb_profile_link:
      "https://www.facebook.com/share/1fDyyUv8Sa/?mibextid=wwXIfr",
  },
  {
    name: "Towfiqul Islam Chowdhury",
    id: "2404077",
    home: "Noakhali",
    college: "Uttara High School and College",
    school: "Uttara High School and College",
    bio: "There's nothing interesting about me and my life , but for me life so hard, rude and unfair.",
    nickname: "TOWFIQ",
    fb_profile_link:
      "https://www.facebook.com/Tawfiq.chowdhury.09?mibextid=ZbWKwL",
  },
  {
    name: "Nur Hossain Sakil",
    id: "2404078",
    home: "Feni",
    college: "Feni government",
    school: "Feni Central High school",
    bio: "ami ekta bolod",
    nickname: "Sakil",
    fb_profile_link: "https://www.facebook.com/share/1AtJJ5F7VF/",
  },
  {
    name: "Irfan Kobir Seyam",
    id: "2404079",
    home: "DHAKA",
    college: "Notredame College",
    school: "Shaheed police smrity college",
    bio: "Loser",
    nickname: "Seyam",
    fb_profile_link: "https://www.facebook.com/share/16zHMXLrkB/",
  },
  {
    name: "Rajdeep Biswas",
    id: "2404080",
    home: "Madaripur",
    college: "Madaripur Govt.College",
    school: "United Islamia Govt.High School,Madaripur",
    bio: "passionate about coding, exploring life, and embracing challenges.",
    nickname: "Rajdeep",
    fb_profile_link: "https://www.facebook.com/share/1CP1sboYiJ/",
  },
  {
    name: "Marufa Yesmin",
    id: "2404081",
    home: "Sherpur",
    college: "Sherpur govt. college",
    school: "Nabarun Public School",
    bio: null,
    nickname: "Marufa",
    fb_profile_link: null,
  },
  {
    name: "Dipannita Das",
    id: "2404082",
    home: "Noakhali",
    college: "Holicross College",
    school: "Dr.Khastagir Govt Girls High School",
    bio: "Seeking new horizons-whimsical!!",
    nickname: "Dipannita",
    fb_profile_link: "https://www.facebook.com/share/16q5zcGNue/",
  },
  {
    name: "Mahibay Tamim",
    id: "2404085",
    home: "Sherpur",
    college: "Sherpur Govt. College",
    school: "Nabarun Public School",
    bio: "Fe",
    nickname: "Tamim",
    fb_profile_link: "https://www.facebook.com/share/1754h5WHuo/",
  },
  {
    name: "Md Adnan Talukdar",
    id: "2404086",
    home: "Chittagong",
    college: "Notre Dame College",
    school: "Chittagong Collegiate School",
    bio: "Turning caffeine into code and ideas into reality.",
    nickname: "Adnan",
    fb_profile_link:
      "https://www.facebook.com/share/19EZJVWwfA/?mibextid=wwXIfr",
  },
  {
    name: "Prionto sarker",
    id: "2404089",
    home: "Netrakona",
    college: "Notre Dame College, Dhaka",
    school: "Anjuman Adarsha Govt High School",
    bio: null,
    nickname: "Prionto",
    fb_profile_link: "https://www.facebook.com/share/179nbRhm1P/",
  },
  {
    name: "Khondaker Hasan Mohammad Arik",
    id: "2404090",
    home: "Narsingdi",
    college: "Chattogram Cantonment Public College",
    school: "Chittagong Ideal High School",
    bio: "Minuscule being with sky-high dreams!",
    nickname: "Arik",
    fb_profile_link: "fb.me/HasanMdArik1",
  },
  {
    name: "Mahajob Joyriya Akando",
    id: "2404091",
    home: "Mymensingh",
    college: "Muminunnisa Government Womens' College",
    school: "Vidyamoyee Government Girls' High School",
    bio: "Mahajob Joyriya",
    nickname: "Joyriya",
    fb_profile_link: null,
  },
  {
    name: "Siam Mondol",
    id: "2404092",
    home: "Pangsha, Rajbari,Dhaka",
    college: "Government science college",
    school: "Machpara High school",
    bio: null,
    nickname: "Siam",
    fb_profile_link: "https://www.facebook.com/share/14H5iHJTVBr/",
  },
  {
    name: "Syeda Tahsina Alam Anikah",
    id: "2404093",
    home: "Sylhet",
    college: "Sylhet Government Womens College",
    school: "Blue Bird High School and College",
    bio: null,
    nickname: "Anikah",
    fb_profile_link: "https://www.facebook.com/share/1ANgMfXsBY/",
  },
  {
    name: "Nur Mohammod Yousuf",
    id: "2404094",
    home: "Cumilla",
    college: "Government Science College",
    school: null,
    bio: null,
    nickname: "Yousuf",
    fb_profile_link: "https://www.facebook.com/nur.mohammad.yousuf.2025",
  },
  {
    name: "Anika sultana Arshi",
    id: "2404096",
    home: "Mymensingh",
    college: "Agriculture university college",
    school: "Agriculture university high school",
    bio: "Hodophile",
    nickname: "Arshi",
    fb_profile_link: "https://www.facebook.com/share/1ET5A2z1wL/",
  },
  {
    name: "Md Rihan",
    id: "2404097",
    home: "Sherpur",
    college: "Agricultural University College, Mymensingh",
    school: "Varera SP School and College",
    bio: null,
    nickname: "Rihan",
    fb_profile_link: "https://www.facebook.com/share/1A8TqoBcM9/",
  },
  {
    name: "S.M. Shahnewas Ahmed",
    id: "2404098",
    home: "Narail",
    college: "BAF Shaheen College Dhaka",
    school: "Tongi Pilot School and Girls College",
    bio: null,
    nickname: "Sakib",
    fb_profile_link: null,
  },
  {
    name: "Rayhan Ferdous",
    id: "2404099",
    home: "Cumilla",
    college: "Cumilla Shikkha Board Govt Model College",
    school: "Cumilla Shikkha Board Govt Model College",
    bio: null,
    nickname: "Rayhan",
    fb_profile_link: "https://www.facebook.com/share/1J5A1K4Koi/",
  },
  {
    name: "AL MUKSITU",
    id: "2404100",
    home: "Netrakona",
    college: "Notre Dame College, Dhaka",
    school: "Mohangonj Pilot Govt. High School,Mohangonj, Netrakona",
    bio: null,
    nickname: "Prachurjo",
    fb_profile_link: "https://www.facebook.com/share/159u1c9cdR/",
  },
  {
    name: "MD HABIBUR RAHAMAN HABIB",
    id: "2404101",
    home: "DINAJPUR",
    college: "IDC",
    school: "CCRS",
    bio: null,
    nickname: "HABIB",
    fb_profile_link: null,
  },
  {
    name: "Shoham Mallick",
    id: "2404102",
    home: "Chattogram",
    college: "Chittagong College",
    school: "Chittagong Collegiate School",
    bio: "Passionate about creating innovative and scalable technology solutions. Skilled in over 7 programming languages, I work across AI/ML, web/app/game development, data analysis, UI/UX, and cybersecurity. I strive to combine technical expertise with creativity to solve real-world problems and contribute to impactful projects.",
    nickname: "Shoham",
    fb_profile_link: "https://www.facebook.com/share/19uJFo1sKz/",
  },
  {
    name: "Md.Ahad Nur",
    id: "2404103",
    home: "Chattogram",
    college: "Barabkund College",
    school: "Sitakund Government Model High School",
    bio: null,
    nickname: "Ahad",
    fb_profile_link: "https://www.facebook.com/share/1JHDs9MUHx/",
  },
  {
    name: "Syeda lubaina morshed tuba",
    id: "2404104",
    home: "Chittagong",
    college: "chittagong goverment city college",
    school: "Bangladesh mahila samity girl's high school and college",
    bio: "Student",
    nickname: "Tuba",
    fb_profile_link: "https://www.facebook.com/share/1ZmbaBvqdm/",
  },
  {
    name: "Saiful Islam",
    id: "2404105",
    home: "Chittagong",
    college: "Kazem Ali school and college",
    school: "Baitush Sharaf Adarsha Kamil Madrasa",
    bio: "Nothing interesting. Just love to explore, play and yeah sometimes code.",
    nickname: "Saiful",
    fb_profile_link: "https://www.facebook.com/share/1HzpHLE5Xa/",
  },
  {
    name: "Md Shakhayet hossan Shihab",
    id: "2404106",
    home: "Cumilla",
    college: "Dhaka imperial College",
    school: "Ibn taimiya school and College",
    bio: null,
    nickname: "Shihab",
    fb_profile_link: "https://www.facebook.com/share/16pqCYWDWh/",
  },
  {
    name: "Md. Ikbal Hossain Siam",
    id: "2404107",
    home: "Cumilla",
    college: "Cumilla Victoria Government College",
    school: "Burichang Ananda Pilot Govt. High School",
    bio: null,
    nickname: "Ikbal",
    fb_profile_link: "https://www.facebook.com/ikbal.siam.7",
  },
  {
    name: "Pritom Halder",
    id: "2404108",
    home: "Satkhira,Khulna",
    college: "Khulna Govt. College",
    school: "Nakipur Govt. H.C Pilot Model High School",
    bio: "Jab tak zinda hoon tab tak mara nahi.. Jab mar gaya, sala main hi nahi..Toh phir darr kis baat ka🗿",
    nickname: "Babu",
    fb_profile_link: "https://www.facebook.com/pritom.halder.238446",
  },
  {
    name: "SHOAIB HASSAN CHOUDRY",
    id: "2404109",
    home: "MYMENSINGH",
    college: "SHAHID SMRITY GOVT. COLLEGE",
    school: "NABARUN BIDYANIKETON",
    bio: null,
    nickname: "SHOAIB",
    fb_profile_link:
      "https://www.facebook.com/share/1LzapNNPSw/?mibextid=wwXIfr",
  },
  {
    name: "MAZEDUR RAHMAN",
    id: "2404110",
    home: "Feni",
    college: "Mohipal Government College",
    school: "Feni Government Pilot High School",
    bio: null,
    nickname: "Mahin",
    fb_profile_link: "https://www.facebook.com/PlASMA.41",
  },
  {
    name: "M.D. Khairul Islam",
    id: "2404111",
    home: "Patuakhali",
    college: "B.A.F Shaheen College,Kurmitola",
    school: "Banani Bidyaniketan School and College",
    bio: null,
    nickname: "Khairul",
    fb_profile_link: "https://www.facebook.com/share/1CkRuJNcBT/",
  },
  {
    name: "Md Ridwan",
    id: "2404112",
    home: "Chittagong",
    college: "Bakalia Govt college",
    school: "Shah Waliullah Institute",
    bio: "Trying to do better ...",
    nickname: "Ridwan",
    fb_profile_link: "https://www.facebook.com/share/1FQz7aF2ae/",
  },
  {
    name: "Rajat Bhattacharjee",
    id: "2404118",
    home: "Chattogram",
    college: "Bakalia Govt College",
    school: "Chattogram Collegiate School",
    bio: null,
    nickname: "Rajat",
    fb_profile_link: "https://www.facebook.com/share/15j2J1whxt/",
  },
  {
    name: "Farhan Wahid",
    id: "2404121",
    home: "Dhaka",
    college: "Dhaka College",
    school: "Motijheel Government Boys High School",
    bio: null,
    nickname: "Farhan",
    fb_profile_link: "https://www.facebook.com/share/1AygsdxC7F/",
  },
  {
    name: "Ashraful alam fahim",
    id: "2404122",
    home: "Brahmanbaria",
    college: "Shashidal Al-haz MD Abu taher college",
    school: "Kasba poura high school",
    bio: "Not interested",
    nickname: "Fahim",
    fb_profile_link: "https://www.facebook.com/ashraf.fahim.9803",
  },
  {
    name: "Arafat",
    id: "2404123",
    home: "Sirajganj",
    college: "Rajshahi College",
    school: "BL Govt High School, Sirajganj",
    bio: null,
    nickname: "Arafat",
    fb_profile_link: "facebook.com/arafat01rahman",
  },
  {
    name: "ABDUL KADER",
    id: "2404124",
    home: "CUMILLA",
    college: "CUMILLA GOVERNMENT COLLEGE",
    school: "IBN TAIMIYA SCHOOL AND COLLEGE",
    bio: null,
    nickname: "KADER",
    fb_profile_link: "https://www.facebook.com/share/1F4sZje34d/",
  },
  {
    name: "Tapon Chandra Barmon",
    id: "2404125",
    home: "Gaibandha",
    college: "Bhatgram High School and College",
    school: "Khordo Komor Pur M.L High School",
    bio: "Just a simple boy",
    nickname: "Tapon",
    fb_profile_link: "https://www.facebook.com/tapana.barmana.789593",
  },
  {
    name: "Muhammad Mustafa Rahib",
    id: "2404126",
    home: "Chattogram",
    college: "Govt. Hazi Muhammad Mohsin College, Chattogram",
    school: "Hathazari Parbati Model Govt. High School",
    bio: null,
    nickname: "Rahib",
    fb_profile_link: "https://www.facebook.com/share/1GdyDWtnNN/",
  },
  {
    name: "Tausif Ibne Monju",
    id: "2404130",
    home: "Kushtia",
    college: "Dhaka Residential Model College",
    school: "Dhaka Residential Model College",
    bio: "Just keeping it up with everything.",
    nickname: "Tausif",
    fb_profile_link:
      "https://www.facebook.com/share/1CsLRTaw5d/?mibextid=wwXIfr",
  },
  {
    name: "Chiranjith Chakma",
    id: "2404132",
    home: "Bandarban, Chittagong",
    college: "Mohammadpur Government College",
    school: "Bandarban Collectorate School and College",
    bio: "I'm on my way to do something different in life, not following the usual path.",
    nickname: "Chiranjith",
    fb_profile_link: "https://www.facebook.com/share/1CCJEVE6Hc/",
  },
];

export const studentsList = [
  { student_id: "2404001", full_name: "ANIKA TABASSUM" },
  { student_id: "2404002", full_name: "HAFSA KHANOM" },
  { student_id: "2404003", full_name: "MD. ABRAR FAIRUJ RAIYAN" },
  { student_id: "2404004", full_name: "TAHMID MOONTAKA" },
  { student_id: "2404005", full_name: "SAYANTAN SEN SARMA" },
  { student_id: "2404006", full_name: "MD. MONTASIR SHAKIL" },
  { student_id: "2404007", full_name: "SK. TASMIA AKTER" },
  { student_id: "2404008", full_name: "TAHIA RABAB" },
  { student_id: "2404009", full_name: "MD. SAZZAT NUR" },
  { student_id: "2404010", full_name: "TANJILA KAMAL" },
  { student_id: "2404011", full_name: "MOHTASIM BHUIYAN MIKAT" },
  { student_id: "2404012", full_name: "ALIKUL ISLAM ALIF" },
  { student_id: "2404013", full_name: "JOYEE DEV" },
  { student_id: "2404014", full_name: "TAMANNA KHANAM JOTI" },
  { student_id: "2404015", full_name: "SAMIYA AHMED CHOWDHURY" },
  { student_id: "2404016", full_name: "MD. JOMMAN" },
  { student_id: "2404017", full_name: "SOUMIK DUTTA" },
  { student_id: "2404018", full_name: "MUQSET HOSSAIN MAHIN" },
  { student_id: "2404019", full_name: "SHARID SHAHRIA" },
  { student_id: "2404020", full_name: "RAHUL BANIK" },
  { student_id: "2404021", full_name: "MD ABDULLAH AZIZ" },
  { student_id: "2404022", full_name: "ADITYA MITRA" },
  { student_id: "2404023", full_name: "MOHAMMAD ADNAN FOISAL" },
  { student_id: "2404024", full_name: "PRAPTI ROY CHOWDHURY" },
  { student_id: "2404025", full_name: "FARDIN KHAN RIFAT" },
  { student_id: "2404026", full_name: "FARHANA AKTER SRETY" },
  { student_id: "2404027", full_name: "MOHAMMAD EKRA" },
  { student_id: "2404028", full_name: "SOUVIK BISWAS" },
  { student_id: "2404029", full_name: "ARPITA BAISHNAB" },
  { student_id: "2404030", full_name: "CHOMOK DATTA" },
  { student_id: "2404031", full_name: "TASLIMA JAHAN BITHI" },
  { student_id: "2404032", full_name: "TONOY CHANDRA PAL" },
  { student_id: "2404033", full_name: "PALASH BISWAS" },
  { student_id: "2404034", full_name: "ANIK DEY" },
  { student_id: "2404035", full_name: "RUPAK CHAKRABARTY ANKON" },
  { student_id: "2404036", full_name: "ISRAT JAHAN" },
  { student_id: "2404037", full_name: "RAFSAN AHMED" },
  { student_id: "2404038", full_name: "FAHIM MUNTASIR TUHIN" },
  { student_id: "2404039", full_name: "ARIAN AHMED ROBI" },
  { student_id: "2404040", full_name: "PAYEL MALLICK" },
  { student_id: "2404041", full_name: "SURAVY RANI DATTA" },
  { student_id: "2404042", full_name: "NUSRAT JAHAN MAYA" },
  { student_id: "2404043", full_name: "ARUNAV DIP ARKO" },
  { student_id: "2404044", full_name: "MD. MAHFUZ HASAN" },
  { student_id: "2404045", full_name: "MD. TANVIR RANA TUHIN" },
  { student_id: "2404046", full_name: "MD. MAHMUDUL HASAN" },
  { student_id: "2404047", full_name: "AFIF AL HASNAIN" },
  { student_id: "2404048", full_name: "RIHAN RAHMAN ABIR" },
  { student_id: "2404049", full_name: "KHADIZA TUL KUBRA TODRA" },
  { student_id: "2404050", full_name: "SUVHA TABASSUM" },
  { student_id: "2404051", full_name: "KHANDAKER BADAR UDDIN MUNIM" },
  { student_id: "2404052", full_name: "SADIA SULTANA" },
  { student_id: "2404053", full_name: "PROTHOY MALLICK" },
  { student_id: "2404054", full_name: "MOHD TAJ UDDIN MAHMUD CHY ABIR" },
  { student_id: "2404055", full_name: "MD HASIBUL KABIR" },
  { student_id: "2404056", full_name: "UMME SALMA" },
  { student_id: "2404057", full_name: "RAHIMUL HOQUE" },
  { student_id: "2404058", full_name: "PUSPITA DASH" },
  { student_id: "2404059", full_name: "IFRAT JAHAN CHOWDHURY" },
  { student_id: "2404060", full_name: "UMME RUBAIYAT TRINA" },
  { student_id: "2404061", full_name: "MD. TANVEER ISLAM JISHAN" },
  { student_id: "2404062", full_name: "SUMAYA SADATH RODIA" },
  { student_id: "2404063", full_name: "MD. RAKIBUL ISLAM RAKIB" },
  { student_id: "2404064", full_name: "A.K.M. MUSFIQUL ISLAM" },
  { student_id: "2404065", full_name: "S. M. MAHDI HASAN" },
  { student_id: "2404066", full_name: "SHISHIR BASAK" },
  { student_id: "2404067", full_name: "TASFIA TABASSUM" },
  { student_id: "2404068", full_name: "TITHI MUTSUDDI" },
  { student_id: "2404069", full_name: "MD. ARMAN KHAN" },
  { student_id: "2404070", full_name: "OMAR AZMAYEEN" },
  { student_id: "2404071", full_name: "PALLABI RANI PAUL" },
  { student_id: "2404072", full_name: "MD. NAZMUS SAKIB" },
  { student_id: "2404073", full_name: "ANTAR KARMAKAR AORGHA" },
  { student_id: "2404074", full_name: "AHNAB AHMED" },
  { student_id: "2404075", full_name: "SIDDHARTHA ROY UTSA" },
  { student_id: "2404076", full_name: "NUHA BINTE MOZAHER" },
  { student_id: "2404077", full_name: "TOWFIQUL ISLAM CHOWDHURY" },
  { student_id: "2404078", full_name: "NUR HOSSAIN SAKIL" },
  { student_id: "2404079", full_name: "IRFAN KOBIR SEYAM" },
  { student_id: "2404080", full_name: "RAJDEEP BISWAS" },
  { student_id: "2404081", full_name: "MARUFA YESMIN" },
  { student_id: "2404082", full_name: "DIPANNITA DAS" },
  { student_id: "2404083", full_name: "TANDRE DHAR" },
  { student_id: "2404084", full_name: "MD. TAHMID BHUIYAN" },
  { student_id: "2404085", full_name: "MAHIBAY TAMIM" },
  { student_id: "2404086", full_name: "MD ADNAN TALUKDAR" },
  { student_id: "2404087", full_name: "RIFAT SHAHRIAR ZIM" },
  { student_id: "2404088", full_name: "MEHEDI HASAN" },
  { student_id: "2404089", full_name: "PRIONTO SARKER" },
  { student_id: "2404090", full_name: "KHONDAKER HASAN MOHAMMAD ARIK" },
  { student_id: "2404091", full_name: "MAHAJOB JOYRIYA AKANDO" },
  { student_id: "2404092", full_name: "SIAM MONDOL" },
  { student_id: "2404093", full_name: "SYEDA TAHSINA ALAM ANIKAH" },
  { student_id: "2404094", full_name: "NUR MOHAMMOD YOUSUF" },
  { student_id: "2404095", full_name: "MD. BHUYAIN EHSAN KABIR" },
  { student_id: "2404096", full_name: "ANIKA SULTANA ARSHI" },
  { student_id: "2404097", full_name: "MD.RIHAN" },
  { student_id: "2404098", full_name: "S. M. SHAHNEWAS AHMED" },
  { student_id: "2404099", full_name: "MD RAYHAN FERDOUS" },
  { student_id: "2404100", full_name: "AL MUKSITU" },
  { student_id: "2404101", full_name: "MD. HABIBUR RAHAMAN HABIB" },
  { student_id: "2404102", full_name: "SHOHAM MALLICK" },
  { student_id: "2404103", full_name: "MD. AHAD NUR" },
  { student_id: "2404104", full_name: "SYEDA LUBAINA MORSHED" },
  { student_id: "2404105", full_name: "MD. SAIFUL ISLAM" },
  { student_id: "2404106", full_name: "MD SHAKHAYET HOSSAN SHIHAB" },
  { student_id: "2404107", full_name: "MD. IKBAL HOSSAIN SIAM" },
  { student_id: "2404108", full_name: "PRITOM HALDER" },
  { student_id: "2404109", full_name: "SHOAIB HASSAN CHOUDRY" },
  { student_id: "2404110", full_name: "MAZEDUR RAHMAN" },
  { student_id: "2404111", full_name: "MD. KHAIRUL ISLAM" },
  { student_id: "2404112", full_name: "MD. RIDWAN" },
  { student_id: "2404113", full_name: "NANGIBA FAYZA KAMAL OHI" },
  { student_id: "2404114", full_name: "TRISHA RAHA" },
  { student_id: "2404115", full_name: "MD. READWAN ULLAH" },
  { student_id: "2404116", full_name: "MD. SIAM HOSSAIN" },
  { student_id: "2404117", full_name: "SIDRATUL MUNTAHA" },
  { student_id: "2404118", full_name: "RAJAT BHATTACHARJEE" },
  { student_id: "2404119", full_name: "PRITOM DAS" },
  { student_id: "2404120", full_name: "MD. MASHIUR RAHMAN TONMOY" },
  { student_id: "2404121", full_name: "FARHAN WAHID" },
  { student_id: "2404122", full_name: "ASRAFUL ALAM FAHIM" },
  { student_id: "2404123", full_name: "ARAFAT" },
  { student_id: "2404124", full_name: "ABDUL KADER" },
  { student_id: "2404125", full_name: "TAPON CHANDRA BARMON" },
  { student_id: "2404126", full_name: "MUHAMMAD MUSTAFA RAHIB" },
  { student_id: "2404127", full_name: "AYESHA KARIM SOHA" },
  { student_id: "2404128", full_name: "FAIYAZ MUHTADI" },
  { student_id: "2404129", full_name: "MD. NAHIAN TANJIM LABIB" },
  { student_id: "2404130", full_name: "TAUSIF IBNE MONJU" },
  { student_id: "2404131", full_name: "ASTIM CHAKMA" },
  { student_id: "2404132", full_name: "CHIRANJITH CHAKMA" },
];

// Note: fbProfileLinks removed - all Facebook links are already in membersArray as fb_profile_link
// This eliminates ~60 lines of redundant data
